services:
  juanos:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: juanos
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=juanos.local
      - VIRTUAL_PORT=3000
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
